---
version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.3
    steps:
      - checkout
      - restore_cache:
          keys:
            - vendor-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - vendor-{{ .Branch }}
            - vendor
      - run:
          name: bundle install
          command: bundle install --path=vendor/bundle --jobs=4 --retry=3
      - save_cache:
          key: vendor-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - restore_cache:
          keys:
            - articles-{{ .Branch }}
            - articles
      - run:
          name: Build static pages
          command: bundle exec middleman build
      - save_cache:
          key: articles-{{ .Branch }}
          paths:
            - build
  deploy:
    docker:
      - image: circleci/ruby:2.4.3
    steps:
      - run:
          name: deploy to s3
          command: bundle exec middleman s3_sync

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          filters:
            branches:
              only:
                - master
          requires:
            - build
