---
version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/ruby:2.4.3
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          keys:
            - vendor-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - vendor-{{ .Branch }}-
            - vendor-
      - run:
          name: bundle install
          command: bundle install --path=vendor/bundle --jobs=4 --retry=3
      - save_cache:
          key: vendor-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - restore_cache:
          keys:
            - articles-{{ .Branch }}
            - articles
      - run:
          name: Build static pages
          command: bundle exec middleman build
      - save_cache:
          key: articles-{{ .Branch }}
          paths:
            - build
      - persist_to_workspace:
          root: ~/repo
          paths:
            - vendor/bundle
            - build
  deploy:
    working_directory: ~/repo
    docker:
      - image: circleci/ruby:2.4.3
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run:
          name: bundle install
          command: bundle install --path=vendor/bundle
      - run:
          name: Install awscli
          command: |
            sudo apt-get update
            sudo apt-get install -y awscli
      - run:
          name: deploy to s3
          command: bundle exec middleman s3_sync
      - run:
          name: Invalidate Cloudfront Caches
          command: |
            aws cloudfront create-invalidation \
              --distribution-id $CLOUDFRONT_DISTRIBUTION_ID \
              --paths /

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          filters:
            branches:
              only:
                - master
          requires:
            - build
