---
version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.3.2
  slack: circleci/slack@4.4.2

executors:
  default:
    working_directory: ~/project
    docker:
      - image: cimg/ruby:2.7.6-node
    environment:
      BUNDLE_APP_CONFIG: ~/project/.bundle/

commands:
  bundle_install:
    parameters:
      bundle_cache_version:
        type: string
        default: v6
    steps:
      - run:
          name: Update bundler to latest
          command: |
            gem update bundler
            bundle --version
      - run:
          name: bundle config
          command: |
            bundle config set --local frozen true
            bundle config set --local path vendor/bundle
            bundle config set --local clean true
      - restore_cache:
          keys:
            - bundler-<< parameters.bundle_cache_version >>-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - bundler-<< parameters.bundle_cache_version >>-{{ .Branch }}
            - bundler-<< parameters.bundle_cache_version >>-master
      - run: bundle install
      - save_cache:
          key: bundler-<< parameters.bundle_cache_version >>-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
  npm_install:
    parameters:
      npm_cache_version:
        type: string
        default: v4
    steps:
      - restore_cache:
          keys:
            - npm-<< parameters.npm_cache_version >>-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - npm-<< parameters.npm_cache_version >>-{{ .Branch }}
            - npm-<< parameters.npm_cache_version >>-master
      - run: npm install
      - save_cache:
          key: npm-<< parameters.npm_cache_version >>-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

jobs:
  lint:
    executor:
      name: default
    steps:
      - checkout
      - bundle_install
      - npm_install
      - run:
          command: bundle exec rubocop
          when: always
      - run:
          command: bundle exec erblint source/**/*.erb
          when: always
      - run:
          command: npm run markdownlint
          when: always
      - run:
          command: npm run eslint
          when: always
      - run:
          command: npm run stylelint
          when: always
      - run:
          command: npx textlint source/posts/
          when: always
  build:
    executor:
      name: default
    parameters:
      article_cache_version:
        type: string
        default: v2
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Install imagemagick for favicon_maker
          command: |
            sudo apt-get update
            sudo apt-get install -y imagemagick
      - bundle_install
      - npm_install
      - restore_cache:
          keys:
            - articles-<< parameters.article_cache_version >>-{{ .Branch }}-{{ .Revision }}
            - articles-<< parameters.article_cache_version >>-{{ .Branch }}
      - run:
          name: Build static pages
          command: bundle exec middleman build
      - run:
          name: Build static pages with verbose output
          when: on_fail
          command: bundle exec middleman build --verbose
      - save_cache:
          key: articles-<< parameters.article_cache_version >>-{{ .Branch }}-{{ .Revision }}
          paths:
            - build
            - .cache
      - persist_to_workspace:
          root: ~/project
          paths:
            - vendor/bundle
            - build
            - Gemfile.lock
  deploy:
    executor:
      name: default
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - bundle_install
      - npm_install
      - aws-cli/install
      - deploy:
          name: deploy to s3
          command: |
            aws s3 sync --delete build s3://queryok.ikuwow.com/
      - deploy:
          name: Invalidate Cloudfront Caches
          command: |
            echo "Distribution ID: ${CLOUDFRONT_DISTRIBUTION_ID}"
            aws cloudfront create-invalidation \
              --distribution-id $CLOUDFRONT_DISTRIBUTION_ID \
              --paths "/*"


workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - lint
      - deploy:
          context: slack-notification
          filters:
            branches:
              only:
                - master
          requires:
            - build
            - lint
          post-steps:
            - slack/notify:
                event: fail
                template: basic_fail_1
            - slack/notify:
                event: pass
                template: success_tagged_deploy_1
