---
version: 2.1

executors:
  default:
    working_directory: ~/project
    docker:
      - image: circleci/ruby:2.5.5-node
    environment:
      BUNDLE_APP_CONFIG: ~/project/.bundle/

commands:
  configure_bundler:
    steps:
      - run: gem update bundler
  restore_gem_cache:
    steps:
      - restore_cache:
          keys:
            - bundler-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - bundler-{{ .Branch }}-
            - bundler-
  save_gem_cache:
    steps:
      - save_cache:
          key: bundler-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
  restore_npm_cache:
    steps:
      - restore_cache:
          keys:
            - npm-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - npm-{{ .Branch }}-
            - npm-
  save_npm_cache:
    steps:
      - save_cache:
          key: npm-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules/

jobs:
  build:
    executor:
      name: default
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - configure_bundler
      - restore_gem_cache
      - run: bundle install
      - save_gem_cache
      - restore_npm_cache
      - run: npm i
      - save_npm_cache
      - restore_cache:
          keys:
            - articles-{{ .Branch }}-{{ .Revision }}
            - articles-{{ .Branch }}
            - articles
      - run:
          name: Build static pages
          command: bundle exec middleman build
      - save_cache:
          key: articles-{{ .Branch }}-{{ .Revision }}
          paths:
            - build
      - persist_to_workspace:
          root: ~/project
          paths:
            - vendor/bundle
            - build
            - Gemfile.lock
  deploy:
    executor:
      name: default
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - configure_bundler
      - restore_gem_cache
      - run: bundle install
      - save_gem_cache
      - run:
          name: Install awscli
          command: |
            sudo apt-get update
            sudo apt-get install -y python-pip python-dev
            sudo pip install awscli --upgrade
            aws configure set preview.cloudfront true
      - run:
          name: deploy to s3
          command: bundle exec middleman s3_sync
      - run:
          name: Invalidate Cloudfront Caches
          command: |
            echo "Distribution ID: ${CLOUDFRONT_DISTRIBUTION_ID}"
            aws cloudfront create-invalidation \
              --distribution-id $CLOUDFRONT_DISTRIBUTION_ID \
              --paths /

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          filters:
            branches:
              only:
                - master
          requires:
            - build
