name: Code Review

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize
      - ready_for_review
      - reopened
    paths-ignore:
      - 'source/posts/**'

jobs:
  code_review:
    if: ${{ github.event.pull_request.draft == false && github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Code Review GPT
        uses: mattzcarey/shippie@v0.12.0
        with:
          MODEL_STRING: 'openai:o3-mini'
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ github.token }}
