name: Lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Super-Linter
        uses: github/super-linter@v3.14.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
